# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_elev', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EarliestSurge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('direction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElevTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('elemNum', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaxElev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemNum', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaxSurge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxSurge_id', models.IntegerField(unique=True)),
                ('kmlFile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('customFile', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.SurgeEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('town_id', models.IntegerField(primary_key=True, serialize=False)),
                ('town_name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TriangleElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_1', models.FloatField()),
                ('y_1', models.FloatField()),
                ('x_2', models.FloatField()),
                ('y_2', models.FloatField()),
                ('x_3', models.FloatField()),
                ('y_3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Typhoon',
            fields=[
                ('typhoon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('typhoon_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='surgeevent',
            name='typhoon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.Typhoon'),
        ),
        migrations.AddField(
            model_name='maxsurge',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.SurgeEvent'),
        ),
        migrations.AddField(
            model_name='elevtimeseries',
            name='typhoon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.Typhoon'),
        ),
        migrations.AddField(
            model_name='earliestsurge',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.SurgeEvent'),
        ),
        migrations.AddField(
            model_name='affectedlocations',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.SurgeEvent'),
        ),
        migrations.AddField(
            model_name='affectedlocations',
            name='town_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.Towns'),
        ),
    ]
