# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeforcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeframe',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='SurgeFrame',
        ),
    ]
