# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeforcast', '0003_surgeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('province_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
    ]
