# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgeforcast', '0004_provinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunCities',
            fields=[
                ('town_id', models.IntegerField(primary_key=True, serialize=False)),
                ('town_name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.SurgeEvent')),
            ],
        ),
    ]
