# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgeforcast', '0005_muncities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muncities',
            old_name='town_id',
            new_name='mun_id',
        ),
        migrations.RenameField(
            model_name='muncities',
            old_name='town_name',
            new_name='mun_name',
        ),
        migrations.AlterField(
            model_name='muncities',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeforcast.Provinces'),
        ),
    ]
